name: Typo-Check-Actions
run-name: Cspell-Action
on:
  push: null
  pull_request: null
jobs:
  spell-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v4
        with:
          files: ""
          check_dot_files: explicit
          root: .
          inline: warning
          strict: true
          incremental_files_only: true
          config: .vscode/cspell.json
          verbose: false
words:
  - fuga
  - fugo
