# https://github.com/marketplace/actions/cspell-action
name: Typo-Check-Actions
run-name: Cspell-Action
on:
  push:
  pull_request:
jobs:
  spell-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v4
        with:
          # github_token: '' # Default: ${{ github.token }}
          files: '' # Default: ALL files
          check_dot_files: explicit # Example: explicit
          root: '.' # Default: .
          inline: warning # Default: warning
          strict: true # Default: true
          incremental_files_only: true # Example: true
          config: '.vscode/cspell.json' # Example: '.'
          verbose: false # Default: false
