name: Typo-Check-Actions
run-name: Cspell-Action
on:
  push:
  pull_request:
jobs:
  spell-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v4
        id: spell-check
        with:
          # github_token: '' # default: ${{ github.token }}
          files: ''
          check_dot_files: explicit
          root: '.'
          inline: warning
          strict: true
          incremental_files_only: true
          config: '.vscode/cspell.json'
          verbose: false