name: Typo-Check-Actions
run-name: Typo-Check
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  Cspell-Action:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v4
        with:
          check_dot_files: explicit
          root: '.'
          inline: warning
          strict: true
          incremental_files_only: true
          config: '.'
          verbose: false