name: Typo-Check-Actions
run-name: Cspell-Action
on:
  push:
  pull_request:
  workflow_dispatch:
jobs:
  spell-check:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: streetsidesoftware/cspell-action@v4
        id: spell-check
        with:
          # github_token: '' # default: ${{ github.token }}
          files: ''
          check_dot_files: explicit
          root: '.'
          inline: error
          strict: false
          incremental_files_only: false # dev
          # incremental_files_only: true
          # config: '.'
          verbose: true
      - name: error-check
        run: |
          echo ${{ steps.spell-check.outputs }}
